name = "clash-merger-cf-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CLASH_KV"
id = "placeholder-kv-id"

[vars]
# TOKEN = "your-secret-token"

[observability]
[observability.logs]
enabled = true
invocation_logs = true